### ISSUE TITLE
Seems to take much longer to build

### ISSUE THREAD

**Issue by dhtdht020** [GayConnect24/advertising-mail#1]
It's been 2 months since I started and it no builds pls help I get this

![image](https://user-images.githubusercontent.com/18469146/48982177-acae0f00-f0e7-11e8-9d6f-f2b82f90e5c2.png)

my screenshot didn't turn out well but you can see the problem anyways so why replace it

I did some research as well and all I found was this

![image](https://user-images.githubusercontent.com/18469146/48982190-d23b1880-f0e7-11e8-91db-0b0c97954210.png)

**Comment by TheMrIron2** [comment]
have you tried turning it off and on again?

**Comment by dhtdht020** [comment]
how do

**Comment by TheMrIron2** [comment]
good
